// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RecruitmentSITHEC;

#nullable disable

namespace RecruitmentSITHEC.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    partial class ApplicationDBContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("RecruitmentSITHEC.Entities.Human", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal>("Altura")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Edad")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(180)
                        .HasColumnType("nvarchar(180)");

                    b.Property<decimal>("Peso")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("Sexo")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Humano", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Altura = 1.80m,
                            Edad = 20,
                            Nombre = "Juan Perez",
                            Peso = 80.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 2,
                            Altura = 1.70m,
                            Edad = 25,
                            Nombre = "Pedro Hernandez",
                            Peso = 70.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 3,
                            Altura = 1.60m,
                            Edad = 30,
                            Nombre = "Maria Santiago",
                            Peso = 60.00m,
                            Sexo = 1
                        },
                        new
                        {
                            Id = 4,
                            Altura = 1.60m,
                            Edad = 35,
                            Nombre = "Jose Perez",
                            Peso = 50.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 5,
                            Altura = 1.80m,
                            Edad = 40,
                            Nombre = "Luis Jimenez",
                            Peso = 50.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 6,
                            Altura = 1.60m,
                            Edad = 45,
                            Nombre = "Ana Alvarado",
                            Peso = 80.00m,
                            Sexo = 1
                        },
                        new
                        {
                            Id = 7,
                            Altura = 1.70m,
                            Edad = 50,
                            Nombre = "Luisa Salazar",
                            Peso = 60.00m,
                            Sexo = 1
                        },
                        new
                        {
                            Id = 8,
                            Altura = 1.70m,
                            Edad = 55,
                            Nombre = "Luis Perez",
                            Peso = 78.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 9,
                            Altura = 1.80m,
                            Edad = 60,
                            Nombre = "Luisa Sanchez",
                            Peso = 56.00m,
                            Sexo = 2
                        },
                        new
                        {
                            Id = 10,
                            Altura = 1.60m,
                            Edad = 65,
                            Nombre = "Maria Salazar",
                            Peso = 45.00m,
                            Sexo = 1
                        },
                        new
                        {
                            Id = 11,
                            Altura = 1.70m,
                            Edad = 70,
                            Nombre = "Maria Lino",
                            Peso = 45.00m,
                            Sexo = 1
                        },
                        new
                        {
                            Id = 12,
                            Altura = 1.60m,
                            Edad = 75,
                            Nombre = "Luisa Perez",
                            Peso = 45.00m,
                            Sexo = 1
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
